# Generated by Django 4.1.6 on 2023-02-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
