# Generated by Django 4.1.6 on 2023-02-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0002_alter_bulletin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
