# Generated by Django 4.1.7 on 2023-02-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0006_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('checked_by', models.CharField(max_length=200)),
                ('t_dsob', models.TimeField()),
                ('r_dsob', models.CharField(max_length=500)),
                ('t_ceu', models.TimeField()),
                ('r_ceu', models.CharField(max_length=500)),
                ('t_cass', models.TimeField()),
                ('r_cass', models.CharField(max_length=500)),
                ('t_uebu', models.TimeField()),
                ('r_uebu', models.CharField(max_length=500)),
                ('t_alicbu', models.TimeField()),
                ('r_alicbu', models.CharField(max_length=500)),
                ('t_ciss', models.TimeField()),
                ('r_ciss', models.CharField(max_length=500)),
                ('t_cpss', models.TimeField()),
                ('r_cpss', models.CharField(max_length=500)),
                ('t_ccrgt', models.TimeField()),
                ('r_ccrgt', models.CharField(max_length=500)),
                ('t_cvti', models.TimeField()),
                ('r_cvti', models.CharField(max_length=500)),
                ('t_ltos', models.TimeField()),
                ('r_ltos', models.CharField(max_length=500)),
            ],
        ),
    ]
