# Generated by Django 4.1.7 on 2023-02-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0007_eveningtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('checked_by', models.CharField(max_length=200)),
                ('t_lits', models.TimeField()),
                ('r_lits', models.CharField(max_length=500)),
                ('t_ciss', models.TimeField()),
                ('r_ciss', models.CharField(max_length=500)),
                ('t_cass', models.TimeField()),
                ('r_cass', models.CharField(max_length=500)),
                ('t_cebu', models.TimeField()),
                ('r_cebu', models.CharField(max_length=500)),
                ('t_boas', models.TimeField()),
                ('r_boas', models.CharField(max_length=500)),
                ('t_cwrge', models.TimeField()),
                ('r_cwrge', models.CharField(max_length=500)),
                ('t_utbeb', models.TimeField()),
                ('r_utbeb', models.CharField(max_length=500)),
                ('t_alicbu', models.TimeField()),
                ('r_alicbu', models.CharField(max_length=500)),
                ('t_ceu', models.TimeField()),
                ('r_ceu', models.CharField(max_length=500)),
                ('t_cdl', models.TimeField()),
                ('r_cdl', models.CharField(max_length=500)),
                ('t_cvti', models.TimeField()),
                ('r_cvti', models.CharField(max_length=500)),
                ('t_cppc', models.TimeField()),
                ('r_cppc', models.CharField(max_length=500)),
                ('t_ccrgt', models.TimeField()),
                ('r_ccrgt', models.CharField(max_length=500)),
            ],
        ),
    ]
