# Generated by Django 4.1.7 on 2023-02-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0008_morningtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveningtask',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
