# Generated by Django 4.1.7 on 2023-02-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0009_alter_eveningtask_time_alter_morningtask_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveningtask',
            name='r_alicbu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='r_cass',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='r_ccrgt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='r_ceu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='r_ciss',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='r_cpss',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='r_cvti',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='r_dsob',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='r_ltos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='r_uebu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='t_alicbu',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='t_cass',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='t_ccrgt',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='t_ceu',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='t_ciss',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='t_cpss',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='t_cvti',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='t_dsob',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='t_ltos',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='t_uebu',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_alicbu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_boas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_cass',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_ccrgt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_cdl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_cebu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_ceu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_ciss',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_cppc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_cvti',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_cwrge',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_lits',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='r_utbeb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_alicbu',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_boas',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_cass',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_ccrgt',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_cdl',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_cebu',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_ceu',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_ciss',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_cppc',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_cvti',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_cwrge',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_lits',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='t_utbeb',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
