# Generated by Django 4.1.7 on 2023-02-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0010_alter_eveningtask_r_alicbu_alter_eveningtask_r_cass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
