# Generated by Django 4.1.7 on 2023-02-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0011_guest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='affected_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='attended_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='time_reported',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='time_resolved',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='tower',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
