# Generated by Django 4.1.7 on 2023-02-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0012_alter_guest_action_alter_guest_affected_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='time_reported',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='time_resolved',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
