# Generated by Django 4.1.7 on 2023-02-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0013_alter_guest_time_alter_guest_time_reported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
