# Generated by Django 4.1.7 on 2023-02-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0014_alter_guest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
