# Generated by Django 4.1.7 on 2023-03-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0015_alter_guest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='time_reported',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='time_resolved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
