# Generated by Django 4.1.7 on 2023-03-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0016_alter_department_date_alter_department_time_reported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='time',
            field=models.TimeField(),
        ),
    ]
