# Generated by Django 4.1.7 on 2023-03-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0017_alter_bulletin_date_alter_bulletin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningtask',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='time',
            field=models.TimeField(),
        ),
    ]
