# Generated by Django 4.1.7 on 2023-03-06 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0019_assets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
    ]
