# Generated by Django 4.1.7 on 2023-03-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0020_rename_assets_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='isAlerted',
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('isThree', 'isThree'), ('isTwo', 'isTwo'), ('isOne', 'isOne'), ('isFresh', 'isFresh')], default='isFresh', max_length=50),
        ),
    ]
