# Generated by Django 4.1.7 on 2023-03-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0022_audit_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='repeat',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='repeat',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
