# Generated by Django 4.1.7 on 2023-03-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0024_rename_repeat_asset_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_tracking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_tracking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
