# Generated by Django 4.1.7 on 2023-03-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0025_asset_current_tracking_date_asset_next_tracking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
