# Generated by Django 4.1.7 on 2023-03-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0026_asset_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='current_tracking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='next_tracking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
