# Generated by Django 4.1.7 on 2023-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0027_audit_current_tracking_date_audit_next_tracking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('supplier', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('expiration', models.DateField()),
                ('schedule', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
