# Generated by Django 4.1.7 on 2023-03-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0030_audit_asset_id_audit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveningtask',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eveningtask',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='morningtask',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
