# Generated by Django 4.1.7 on 2023-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_logs', '0032_audit_modified_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BHTLEveningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('checked_by', models.CharField(max_length=200)),
                ('t_dsob', models.TimeField(blank=True, null=True)),
                ('r_dsob', models.CharField(blank=True, max_length=500, null=True)),
                ('t_ceu', models.TimeField(blank=True, null=True)),
                ('r_ceu', models.CharField(blank=True, max_length=500, null=True)),
                ('t_cass', models.TimeField(blank=True, null=True)),
                ('r_cass', models.CharField(blank=True, max_length=500, null=True)),
                ('t_uebu', models.TimeField(blank=True, null=True)),
                ('r_uebu', models.CharField(blank=True, max_length=500, null=True)),
                ('t_alicbu', models.TimeField(blank=True, null=True)),
                ('r_alicbu', models.CharField(blank=True, max_length=500, null=True)),
                ('t_ciss', models.TimeField(blank=True, null=True)),
                ('r_ciss', models.CharField(blank=True, max_length=500, null=True)),
                ('t_cpss', models.TimeField(blank=True, null=True)),
                ('r_cpss', models.CharField(blank=True, max_length=500, null=True)),
                ('t_ccrgt', models.TimeField(blank=True, null=True)),
                ('r_ccrgt', models.CharField(blank=True, max_length=500, null=True)),
                ('t_cvti', models.TimeField(blank=True, null=True)),
                ('r_cvti', models.CharField(blank=True, max_length=500, null=True)),
                ('t_ltos', models.TimeField(blank=True, null=True)),
                ('r_ltos', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BHTLMorningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('checked_by', models.CharField(max_length=200)),
                ('t_lits', models.TimeField(blank=True, null=True)),
                ('r_lits', models.CharField(blank=True, max_length=500, null=True)),
                ('t_ciss', models.TimeField(blank=True, null=True)),
                ('r_ciss', models.CharField(blank=True, max_length=500, null=True)),
                ('t_cass', models.TimeField(blank=True, null=True)),
                ('r_cass', models.CharField(blank=True, max_length=500, null=True)),
                ('t_cebu', models.TimeField(blank=True, null=True)),
                ('r_cebu', models.CharField(blank=True, max_length=500, null=True)),
                ('t_boas', models.TimeField(blank=True, null=True)),
                ('r_boas', models.CharField(blank=True, max_length=500, null=True)),
                ('t_cwrge', models.TimeField(blank=True, null=True)),
                ('r_cwrge', models.CharField(blank=True, max_length=500, null=True)),
                ('t_utbeb', models.TimeField(blank=True, null=True)),
                ('r_utbeb', models.CharField(blank=True, max_length=500, null=True)),
                ('t_alicbu', models.TimeField(blank=True, null=True)),
                ('r_alicbu', models.CharField(blank=True, max_length=500, null=True)),
                ('t_ceu', models.TimeField(blank=True, null=True)),
                ('r_ceu', models.CharField(blank=True, max_length=500, null=True)),
                ('t_cdl', models.TimeField(blank=True, null=True)),
                ('r_cdl', models.CharField(blank=True, max_length=500, null=True)),
                ('t_cvti', models.TimeField(blank=True, null=True)),
                ('r_cvti', models.CharField(blank=True, max_length=500, null=True)),
                ('t_cppc', models.TimeField(blank=True, null=True)),
                ('r_cppc', models.CharField(blank=True, max_length=500, null=True)),
                ('t_ccrgt', models.TimeField(blank=True, null=True)),
                ('r_ccrgt', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
